"""empty message

Revision ID: 0508fe9ffe3d
Revises: ec16aefe0020
Create Date: 2023-05-23 18:31:48.197496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0508fe9ffe3d'
down_revision = 'ec16aefe0020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast_ethnicity_source_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_link_id', sa.Integer(), nullable=True),
    sa.Column('cast_ethnicity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_ethnicity_id'], ['cast_ethnicities.id'], ),
    sa.ForeignKeyConstraint(['source_link_id'], ['source_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cast_ethnicities', schema=None) as batch_op:
        batch_op.drop_constraint('cast_ethnicities_source_id_fkey', type_='foreignkey')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('source_links', schema=None) as batch_op:
        batch_op.drop_constraint('source_links_cast_ethnicity_id_fkey', type_='foreignkey')
        batch_op.drop_column('cast_ethnicity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cast_ethnicity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('source_links_cast_ethnicity_id_fkey', 'cast_ethnicities', ['cast_ethnicity_id'], ['id'])

    with op.batch_alter_table('cast_ethnicities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cast_ethnicities_source_id_fkey', 'source_links', ['source_id'], ['id'])

    op.drop_table('cast_ethnicity_source_links')
    # ### end Alembic commands ###
