"""empty message

Revision ID: 308408a8a8ef
Revises: dfd6c723d08b
Create Date: 2023-05-24 14:54:38.155566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308408a8a8ef'
down_revision = 'dfd6c723d08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('also_known_as',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cast_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('also_known_as')
    # ### end Alembic commands ###
