"""empty message

Revision ID: 6edd3cbc34c8
Revises: 
Create Date: 2023-05-17 09:09:01.026254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edd3cbc34c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_path', sa.String(length=35), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.drop_column('profile_path')

    # ### end Alembic commands ###
