"""empty message

Revision ID: 9af4fe928bee
Revises: 08b13cbdae34
Create Date: 2023-05-30 15:28:37.936103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af4fe928bee'
down_revision = '08b13cbdae34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=75),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=75),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
