"""initial_schema

Revision ID: 9faf7dda1632
Revises: 
Create Date: 2026-04-12 18:08:27.965113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9faf7dda1632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('imdb_event_id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('imdb_event_id', name=op.f('uq_events_imdb_event_id')),
    sa.UniqueConstraint('name', name=op.f('uq_events_name'))
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genders')),
    sa.UniqueConstraint('name', name=op.f('uq_genders_name'))
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('poster_path', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('short', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races')),
    sa.UniqueConstraint('name', name=op.f('uq_races_name')),
    sa.UniqueConstraint('short', name=op.f('uq_races_short'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('domain', name=op.f('uq_sources_domain')),
    sa.UniqueConstraint('name', name=op.f('uq_sources_name'))
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_awards_event_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awards')),
    sa.UniqueConstraint('event_id', 'name', name='uq_awards_event_id_name')
    )
    op.create_table('media_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_media_genres_genre_id')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_media_genres_movie_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_genres'))
    )
    op.create_table('source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_links_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_links')),
    sa.UniqueConstraint('link', name=op.f('uq_source_links_link'))
    )
    op.create_table('subregions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_subregions_region_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subregions')),
    sa.UniqueConstraint('name', name=op.f('uq_subregions_name'))
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('cca3', sa.String(length=3), nullable=False),
    sa.Column('demonym', sa.String(length=75), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('subregion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_countries_region_id')),
    sa.ForeignKeyConstraint(['subregion_id'], ['subregions.id'], name=op.f('fk_countries_subregion_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('cca3', name=op.f('uq_countries_cca3')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('subregion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subregion_id'], ['subregions.id'], name=op.f('fk_ethnicities_subregion_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ethnicities')),
    sa.UniqueConstraint('name', name=op.f('uq_ethnicities_name'))
    )
    op.create_table('nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_nominations_award_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nominations')),
    sa.UniqueConstraint('award_id', 'year', name='uq_nominations_award_id_year')
    )
    op.create_table('alt_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('alt_name', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_alt_countries_country_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alt_countries')),
    sa.UniqueConstraint('country_id', 'alt_name', name='uq_alt_countries_country_id_alt_name')
    )
    op.create_table('alt_ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethnicity_id', sa.Integer(), nullable=False),
    sa.Column('alt_name', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['ethnicities.id'], name=op.f('fk_alt_ethnicities_ethnicity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alt_ethnicities')),
    sa.UniqueConstraint('ethnicity_id', 'alt_name', name='uq_alt_ethnicities_ethnicity_id_alt_name')
    )
    op.create_table('cast_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('deathday', sa.DateTime(), nullable=True),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('country_of_birth_id', sa.Integer(), nullable=True),
    sa.Column('profile_path', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['country_of_birth_id'], ['countries.id'], name=op.f('fk_cast_members_country_of_birth_id')),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], name=op.f('fk_cast_members_gender_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cast_members'))
    )
    op.create_table('movie_nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_nominations_movie_id')),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], name=op.f('fk_movie_nominations_nomination_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_nominations')),
    sa.UniqueConstraint('movie_id', 'nomination_id', name='uq_movie_nominations_movie_id')
    )
    op.create_table('alt_cast_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cast_member_id', sa.Integer(), nullable=False),
    sa.Column('alt_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], name=op.f('fk_alt_cast_members_cast_member_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alt_cast_members')),
    sa.UniqueConstraint('cast_member_id', 'alt_name', name='uq_alt_cast_members_cast_member_id_alt_name')
    )
    op.create_table('cast_ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethnicity_id', sa.Integer(), nullable=True),
    sa.Column('cast_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], name=op.f('fk_cast_ethnicities_cast_member_id')),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['ethnicities.id'], name=op.f('fk_cast_ethnicities_ethnicity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cast_ethnicities'))
    )
    op.create_table('cast_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('cast_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], name=op.f('fk_cast_races_cast_member_id')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_cast_races_race_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cast_races'))
    )
    op.create_table('credits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=75), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('cast_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], name=op.f('fk_credits_cast_member_id')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_credits_movie_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credits'))
    )
    op.create_table('cast_ethnicity_source_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_link_id', sa.Integer(), nullable=False),
    sa.Column('cast_ethnicity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cast_ethnicity_id'], ['cast_ethnicities.id'], name=op.f('fk_cast_ethnicity_source_links_cast_ethnicity_id')),
    sa.ForeignKeyConstraint(['source_link_id'], ['source_links.id'], name=op.f('fk_cast_ethnicity_source_links_source_link_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cast_ethnicity_source_links'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cast_ethnicity_source_links')
    op.drop_table('credits')
    op.drop_table('cast_races')
    op.drop_table('cast_ethnicities')
    op.drop_table('alt_cast_members')
    op.drop_table('movie_nominations')
    op.drop_table('cast_members')
    op.drop_table('alt_ethnicities')
    op.drop_table('alt_countries')
    op.drop_table('nominations')
    op.drop_table('ethnicities')
    op.drop_table('countries')
    op.drop_table('subregions')
    op.drop_table('source_links')
    op.drop_table('media_genres')
    op.drop_table('awards')
    op.drop_table('sources')
    op.drop_table('regions')
    op.drop_table('races')
    op.drop_table('movies')
    op.drop_table('genres')
    op.drop_table('genders')
    op.drop_table('events')
    # ### end Alembic commands ###
