"""empty message

Revision ID: b14a0db2f837
Revises: 0508fe9ffe3d
Create Date: 2023-05-24 14:16:47.269920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14a0db2f837'
down_revision = '0508fe9ffe3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aka',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aka_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'aka', ['aka_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('aka_id')

    op.drop_table('aka')
    # ### end Alembic commands ###
