"""empty message

Revision ID: b95ceb377a3a
Revises: 9af4fe928bee
Create Date: 2023-05-30 15:58:45.184658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95ceb377a3a'
down_revision = '9af4fe928bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.alter_column('character',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=75),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.alter_column('character',
               existing_type=sa.String(length=75),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=75),
               existing_nullable=False)

    # ### end Alembic commands ###
