"""initial schema

Revision ID: d88c7ae29181
Revises: 
Create Date: 2026-03-21 15:54:50.396675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88c7ae29181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.alter_column('character',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    with op.batch_alter_table('movie_nominations', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nomination_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('imdb_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('runtime',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('poster_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('budget',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('revenue',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('nominations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nominations', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('revenue',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('poster_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('runtime',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('overview',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('imdb_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    with op.batch_alter_table('movie_nominations', schema=None) as batch_op:
        batch_op.alter_column('nomination_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)

    # ### end Alembic commands ###
