"""empty message

Revision ID: dfd6c723d08b
Revises: b14a0db2f837
Create Date: 2023-05-24 14:32:41.268963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd6c723d08b'
down_revision = 'b14a0db2f837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('also_known_as',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cast_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_member_id'], ['cast_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('also_known_as_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'also_known_as', ['also_known_as_id'], ['id'])
        batch_op.drop_column('aka_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aka_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('also_known_as_id')

    op.drop_table('also_known_as')
    # ### end Alembic commands ###
