"""empty message

Revision ID: e0b52900e381
Revises: 6edd3cbc34c8
Create Date: 2023-05-22 14:36:31.775640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b52900e381'
down_revision = '6edd3cbc34c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('cast_ethnicity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_ethnicity'], ['cast_ethnicities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alt_ethnicities', schema=None) as batch_op:
        batch_op.alter_column('ethnicity_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cast_ethnicities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'source_links', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_ethnicities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('alt_ethnicities', schema=None) as batch_op:
        batch_op.alter_column('ethnicity_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('sources')
    op.drop_table('source_links')
    # ### end Alembic commands ###
