"""Add unique constraint unique_movie_id_nomination_id

Revision ID: fb2c5325fde2
Revises: b95ceb377a3a
Create Date: 2024-03-22 10:29:02.436130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2c5325fde2'
down_revision = 'b95ceb377a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_nominations', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_movie_id_nomination_id', ['movie_id', 'nomination_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_nominations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_movie_id_nomination_id', type_='unique')

    # ### end Alembic commands ###
